import type { Pirate, Mission } from './types';

export const SAMPLE_PIRATES: Pirate[] = [
  {
    id: 'p1',
    name: "Blackbeard's Shadow",
    age: 42,
    role: 'Captain',
    hp: 95,
    scurvy: 5,
    morale: 92,
    experience: 98,
    skills: { swordsmanship: 95, cannonGunnery: 80, navigation: 90, rigging: 70, stealth: 60, medicine: 30 },
    status: 'Active',
    bio: 'Legendary commander of the Midnight Reaver. Known for tactical brilliance and an iron will that inspires absolute loyalty.',
  },
  {
    id: 'p2',
    name: 'Silas Crow',
    age: 38,
    role: 'Quartermaster',
    hp: 88,
    scurvy: 12,
    morale: 85,
    experience: 90,
    skills: { swordsmanship: 75, cannonGunnery: 50, navigation: 85, rigging: 65, stealth: 80, medicine: 45 },
    status: 'Active',
    bio: 'The captain\'s right hand. Manages plunder distribution and crew discipline with cold precision.',
  },
  {
    id: 'p3',
    name: 'Gunnar Ironhand',
    age: 45,
    role: 'Master Gunner',
    hp: 82,
    scurvy: 25,
    morale: 78,
    experience: 92,
    skills: { swordsmanship: 60, cannonGunnery: 98, navigation: 40, rigging: 50, stealth: 20, medicine: 15 },
    status: 'Active',
    bio: 'A walking encyclopedia of artillery. Can hit a galleon\'s powder magazine from 400 yards in a storm.',
  },
  {
    id: 'p4',
    name: 'Rosa LaSirena',
    age: 28,
    role: 'Lookout',
    hp: 100,
    scurvy: 8,
    morale: 90,
    experience: 65,
    skills: { swordsmanship: 55, cannonGunnery: 20, navigation: 75, rigging: 60, stealth: 95, medicine: 40 },
    status: 'Active',
    bio: 'Eyes like a hawk and moves like smoke. Spots naval patrols before anyone else and vanishes when needed.',
  },
  {
    id: 'p5',
    name: 'Old Tom Barnacle',
    age: 58,
    role: 'Shipwright',
    hp: 65,
    scurvy: 45,
    morale: 55,
    experience: 95,
    skills: { swordsmanship: 30, cannonGunnery: 15, navigation: 60, rigging: 95, stealth: 10, medicine: 70 },
    status: 'Active',
    bio: 'Has kept the Midnight Reaver afloat through three hurricanes and two kraken attacks. The ship IS his life.',
  },
  {
    id: 'p6',
    name: 'Cutter Flynn',
    age: 25,
    role: 'Bosun',
    hp: 92,
    scurvy: 15,
    morale: 88,
    experience: 55,
    skills: { swordsmanship: 85, cannonGunnery: 45, navigation: 50, rigging: 80, stealth: 55, medicine: 20 },
    status: 'Active',
    bio: 'Young but fierce. Commands the deck crew with a voice that carries over any storm and a cutlass that speaks louder.',
  },
  {
    id: 'p7',
    name: 'Mira the Sawbones',
    age: 34,
    role: 'Deckhand',
    hp: 78,
    scurvy: 30,
    morale: 72,
    experience: 60,
    skills: { swordsmanship: 35, cannonGunnery: 10, navigation: 30, rigging: 45, stealth: 40, medicine: 95 },
    status: 'Active',
    bio: 'Unofficial ship surgeon. Can amputate a leg in under two minutes and has saved more crew than anyone alive.',
  },
  {
    id: 'p8',
    name: 'Dread Morgan',
    age: 50,
    role: 'Master Gunner',
    hp: 55,
    scurvy: 60,
    morale: 40,
    experience: 88,
    skills: { swordsmanship: 70, cannonGunnery: 90, navigation: 35, rigging: 40, stealth: 15, medicine: 10 },
    status: 'Wounded',
    bio: 'Veteran gunner with a temper as volatile as his powder charges. His scurvy and wounds slow him but not his aim.',
  },
  {
    id: 'p9',
    name: 'Whisper Kade',
    age: 22,
    role: 'Lookout',
    hp: 100,
    scurvy: 5,
    morale: 95,
    experience: 35,
    skills: { swordsmanship: 40, cannonGunnery: 10, navigation: 65, rigging: 50, stealth: 98, medicine: 25 },
    status: 'Active',
    bio: 'The youngest crew member but already the best infiltrator. Can slip into any port unnoticed and return with intel.',
  },
  {
    id: 'p10',
    name: 'Brine O\'Malley',
    age: 36,
    role: 'Deckhand',
    hp: 70,
    scurvy: 35,
    morale: 60,
    experience: 50,
    skills: { swordsmanship: 65, cannonGunnery: 55, navigation: 45, rigging: 70, stealth: 30, medicine: 20 },
    status: 'Active',
    bio: 'A reliable jack-of-all-trades. Not exceptional at anything but competent at everything — the backbone of the crew.',
  },
  {
    id: 'p11',
    name: 'Scarlet Nunez',
    age: 30,
    role: 'Quartermaster',
    hp: 85,
    scurvy: 18,
    morale: 82,
    experience: 70,
    skills: { swordsmanship: 80, cannonGunnery: 30, navigation: 75, rigging: 55, stealth: 85, medicine: 50 },
    status: 'Active',
    bio: 'Rival quartermaster who handles black market contacts. Her network of informants spans three oceans.',
  },
  {
    id: 'p12',
    name: 'Grog McTavish',
    age: 48,
    role: 'Deckhand',
    hp: 40,
    scurvy: 70,
    morale: 25,
    experience: 75,
    skills: { swordsmanship: 50, cannonGunnery: 40, navigation: 20, rigging: 60, stealth: 5, medicine: 10 },
    status: 'Wounded',
    bio: 'Once a strong worker, now ravaged by scurvy and rum. His morale is dangerously low — keep an eye on him.',
  },
  {
    id: 'p13',
    name: 'Navarre Leclerc',
    age: 33,
    role: 'Bosun',
    hp: 90,
    scurvy: 10,
    morale: 75,
    experience: 68,
    skills: { swordsmanship: 70, cannonGunnery: 35, navigation: 80, rigging: 90, stealth: 45, medicine: 30 },
    status: 'Active',
    bio: 'French-born sail master. Can coax speed from the laziest winds and repairs rigging faster than most can tie a knot.',
  },
  {
    id: 'p14',
    name: 'Jin Wavebreaker',
    age: 27,
    role: 'Shipwright',
    hp: 95,
    scurvy: 3,
    morale: 85,
    experience: 48,
    skills: { swordsmanship: 45, cannonGunnery: 20, navigation: 55, rigging: 88, stealth: 35, medicine: 65 },
    status: 'Active',
    bio: 'Eastern carpenter with innovative hull-reinforcement techniques. His modifications have doubled the ship\'s durability.',
  },
  {
    id: 'p15',
    name: 'Rat Hawkins',
    age: 31,
    role: 'Deckhand',
    hp: 75,
    scurvy: 28,
    morale: 65,
    experience: 52,
    skills: { swordsmanship: 55, cannonGunnery: 60, navigation: 30, rigging: 50, stealth: 70, medicine: 15 },
    status: 'Active',
    bio: 'A former naval deserter who brings insider knowledge of patrol routes and naval tactics to the crew.',
  },
  {
    id: 'p16',
    name: 'Tempest Voss',
    age: 29,
    role: 'Master Gunner',
    hp: 88,
    scurvy: 22,
    morale: 80,
    experience: 62,
    skills: { swordsmanship: 50, cannonGunnery: 92, navigation: 30, rigging: 45, stealth: 25, medicine: 20 },
    status: 'Active',
    bio: 'Rising star in the gunnery crew. Invented the "Voss Volley" — a devastating three-cannon synchronized barrage.',
  },
  {
    id: 'p17',
    name: 'Plume Delacroix',
    age: 40,
    role: 'Deckhand',
    hp: 30,
    scurvy: 80,
    morale: 20,
    experience: 58,
    skills: { swordsmanship: 40, cannonGunnery: 25, navigation: 15, rigging: 35, stealth: 50, medicine: 55 },
    status: 'Wounded',
    bio: 'The crew\'s poet and chronicler, now gravely ill. His scurvy is critical and morale near mutinous. Needs urgent care.',
  },
  {
    id: 'p18',
    name: 'Kira Stormwall',
    age: 26,
    role: 'Lookout',
    hp: 98,
    scurvy: 2,
    morale: 93,
    experience: 40,
    skills: { swordsmanship: 60, cannonGunnery: 15, navigation: 80, rigging: 55, stealth: 88, medicine: 35 },
    status: 'Active',
    bio: 'Fearless climber who volunteers for the crow\'s nest in every storm. Her storm-navigation instincts are unmatched.',
  },
  {
    id: 'p19',
    name: 'Barnaby Cross',
    age: 52,
    role: 'Deckhand',
    hp: 60,
    scurvy: 40,
    morale: 48,
    experience: 82,
    skills: { swordsmanship: 45, cannonGunnery: 55, navigation: 25, rigging: 75, stealth: 20, medicine: 30 },
    status: 'On Leave',
    bio: 'Seasoned deckhand recovering from a shoulder injury. Decades at sea have made him wise but his body is failing.',
  },
  {
    id: 'p20',
    name: 'Zara Blacktide',
    age: 24,
    role: 'Bosun',
    hp: 96,
    scurvy: 6,
    morale: 88,
    experience: 38,
    skills: { swordsmanship: 72, cannonGunnery: 25, navigation: 65, rigging: 85, stealth: 60, medicine: 40 },
    status: 'Active',
    bio: 'Rising prodigy who can reef a sail in record time. Her energy is contagious and crew efficiency soars when she leads.',
  },
];

export const SAMPLE_MISSIONS: Mission[] = [
  {
    id: 'm1',
    name: 'Plunder the Silver Galleon',
    type: 'Merchant Ship Raid',
    difficulty: 3,
    requiredCrewSize: 6,
    requiredSkills: { swordsmanship: 70, cannonGunnery: 60, navigation: 50 },
    riskLevel: 'Medium',
    assignedCrew: [],
    status: 'Planning',
  },
  {
    id: 'm2',
    name: 'Board the HMS Sovereign',
    type: 'Naval Boarding',
    difficulty: 5,
    requiredCrewSize: 8,
    requiredSkills: { swordsmanship: 80, cannonGunnery: 70, stealth: 60, navigation: 60 },
    riskLevel: 'Extreme',
    assignedCrew: [],
    status: 'Planning',
  },
  {
    id: 'm3',
    name: 'Skull Island Recovery',
    type: 'Treasure Island Expedition',
    difficulty: 4,
    requiredCrewSize: 5,
    requiredSkills: { navigation: 75, stealth: 70, rigging: 60, medicine: 50 },
    riskLevel: 'High',
    assignedCrew: [],
    status: 'Planning',
  },
  {
    id: 'm4',
    name: 'Port Royal Infiltration',
    type: 'Silent Harbor Infiltration',
    difficulty: 4,
    requiredCrewSize: 4,
    requiredSkills: { stealth: 85, navigation: 60, swordsmanship: 40 },
    riskLevel: 'High',
    assignedCrew: [],
    status: 'Planning',
  },
  {
    id: 'm5',
    name: 'The Leviathan Hunt',
    type: 'Kraken Hunt',
    difficulty: 5,
    requiredCrewSize: 10,
    requiredSkills: { cannonGunnery: 80, swordsmanship: 70, navigation: 70, rigging: 65, medicine: 60 },
    riskLevel: 'Extreme',
    assignedCrew: [],
    status: 'Planning',
  },
  {
    id: 'm6',
    name: 'Storm Tortuga Garrison',
    type: 'Fort Assault',
    difficulty: 4,
    requiredCrewSize: 7,
    requiredSkills: { cannonGunnery: 75, swordsmanship: 75, rigging: 50, stealth: 40 },
    riskLevel: 'High',
    assignedCrew: [],
    status: 'Planning',
  },
  {
    id: 'm7',
    name: 'Free the Prisoners of Isla Muerte',
    type: 'Rescue Mission',
    difficulty: 3,
    requiredCrewSize: 5,
    requiredSkills: { stealth: 75, medicine: 60, navigation: 55, swordsmanship: 50 },
    riskLevel: 'Medium',
    assignedCrew: [],
    status: 'Planning',
  },
];
